### ISSUE TITLE
我没有找到第三章的Android工程的代码

### ISSUE THREAD

**Issue by Godblessjovi** [cwpeng-cn/pytorch-neural-network-practice#1]
文中有提到Utils中的辅助代码，读者可以在代码仓库中找到，似乎没有。
请问是作者遗漏了，还是我没找对地方？

**Comment by Xiaofeng-life** [comment]
> 文中有提到Utils中的辅助代码，读者可以在代码仓库中找到，似乎没有。 请问是作者遗漏了，还是我没找对地方？

书封底有二维码，扫描关注公众号应该可以下载，如果不行的话at我一下

**Comment by Xiaofeng-life** [comment]
> 文中有提到Utils中的辅助代码，读者可以在代码仓库中找到，似乎没有。 请问是作者遗漏了，还是我没找对地方？
